### ISSUE TITLE
Should return WebApplicationBuilder not WebApplication

### ISSUE THREAD

**Issue by mocox** [tryphotino/photino.NET.Server#2]
Hi

in the PhotinoServer.CreateStaticFileServer(...) it retuns a WebApplication and you cant set services to the value, Surely this method should return A WebApplicationBuilder so that services can be added to the ServiceCollection. I see no way in your samples to add Services, unless i am missing something. 
I copied the code into new local class and amended and can now host my endpoints in same project, couldn't before

**Comment by mocox** [comment]
I used your method but passed back the webapplicationbuilder instead of the webapplication and used DI services and minimalapis and it works fine,

Thanks

**Comment by MikeYeager** [comment]
@mocox I think it comes down to this, we call Build() and then enable default files and static files before returning the app. If we were to change this, it would require that the user make these calls. We're not opposed to adding a new method that returned the builder, but didn't go down that path for this reason.

```csharp
        WebApplication app = builder.Build();
        app.UseDefaultFiles();
        app.UseStaticFiles(new StaticFileOptions { DefaultContentType = "text/plain" });
        return app;
```
